### ISSUE TITLE
Critical exception 

### ISSUE THREAD

**Issue by Ernestopheles** [contao/contao#6012]
### Affected version(s)

4.13.22

### Description

After Update from 4.13.21 var log shows

> {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function Contao\\ManagerBundle\\Command\\ContaoSetupCommand::__construct(), 2 passed

**Comment by fritzmg** [comment]
How exactly is this reproduced?

**Comment by Ernestopheles** [comment]
I get the same error in 5 installations

**Comment by fritzmg** [comment]
> I get the same error in 5 installations

That does not answer the question. What exactly do you do, to reproduce this error?

**Comment by Ernestopheles** [comment]
I did an all package update by CM, then once run the webside then visit the log file

**Comment by aschempp** [comment]
Since this old issue has not been updated in a while, I assume it has been fixed in the meantime.
