### ISSUE TITLE
contao.intl.locales cannot be decorated without inheritance

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#5519]
### Affected version(s)

4.13, 5.0, 5.x

### Description

In https://github.com/contao/contao/pull/3138 we deprecated the `getLanguages` hook:

```
Using the "getLanguages" hook has been deprecated and will no longer work in Contao 5.0. Decorate the "Contao\CoreBundle\Intl\Locales" service instead.
```

However, the `contao.intl.locales` service cannot actually be decorated without inheriting from it, as it does not implement an interface and thus the type `Contao\CoreBundle\Intl\Locales` is needed for dependency injection everywhere else.

Though I think even an interface is imho not a good solution, as the interface would have to consist of all current public methods and thus the decorated service would, at least, need to look like this, just to add some additional languages:

```php
namespace App\Intl;

use Contao\CoreBundle\Intl\LocalesInterface;

class Locales implements LocalesInterface
{
    public function getLocales(string $displayLocale = null, bool $addNativeSuffix = false): array
    {
        $locales = $this->inner->getLocales($displayLocale, $addNativeSuffix);

        // Add your locales here …

        return $locales;
    }

    public function getEnabledLocales(string $displayLocale = null, bool $addNativeSuffix = false): array
    {
        $locales = $this->inner->getEnabledLocaleIds($displayLocale, $addNativeSuffix);

        // Add your locales here …

        return $locales;
    }

    public function getLanguages(string $displayLocale = null, bool $addNativeSuffix = false): array
    {
        return $this->getLanguageLocaleIds($displayLocale, $addNativeSuffix);
    }

    public function getLocaleIds(): array
    {
        return $this->inner->getLocaleIds();
    }

    public function getEnabledLocaleIds(): array
    {
        return $this->inner->getEnabledLocaleIds();
    }

    public function getLanguageLocaleIds(): array
    {
        return $this->inner->getLanguageLocaleIds();
    }

    public function getDisplayNames(array $localeIds, string $displayLocale = null, bool $addNativeSuffix = false): array
    {
        return $this->inner->getDisplayNames($localeIds, $displayLocale, $addNativeSuffix);
    }
}
```

And even with inheritance it is not as convenient as the hook was, since you always need at least two methods (depending on your use case):

```php
namespace App\Intl;

use Contao\CoreBundle\Intl\Locales as ContaoLocales;

class Locales extends ContaoLocales
{
    public function __construct(private ContaoLocales $inner)
    {
    }

    public function getLocales(string $displayLocale = null, bool $addNativeSuffix = false): array
    {
        $locales = $this->inner->getLocales($displayLocale, $addNativeSuffix);

        // Add your locales here …

        return $locales;
    }

    public function getEnabledLocales(string $displayLocale = null, bool $addNativeSuffix = false): array
    {
        $locales = $this->inner->getEnabledLocales($displayLocale, $addNativeSuffix);

        // Add your locales here …

        return $locales;
    }
}
```

Shouldn't we instead introduce an event?

**Comment by fritzmg** [comment]
Decorating the service may be does not work at all. Even with inheritance, I get the following error during cache warmup:

```
Error:
Typed property Contao\CoreBundle\Intl\Locales::$enabledLocales must not be accessed before initialization

  at vendor\contao\core-bundle\src\Intl\Locales.php:148
  at Contao\CoreBundle\Intl\Locales->getEnabledLocaleIds()
     (vendor\contao\core-bundle\src\Cache\ContaoCacheWarmer.php:53)
````

```yaml
# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Intl\Locales:
        decorates: 'contao.intl.locales'
```

**Comment by ausi** [comment]
> since you always need at least two methods

You have to overwrite all public methods, including the ones that you don’t want to change, they need to be forwared to the inner service too.

> Shouldn't we instead introduce an event?

I think we could, but this should only fire once on initialization I think, not on every method call.
What is your use case to change the locales?

**Comment by fritzmg** [comment]
> You have to overwrite all public methods, including the ones that you don’t want to change, they need to be forwared to the inner service too.

The point was that it is currently rather cumbersome to add new languages (or impossible).

> What is your use case to change the locales?

In my case I wanted to add translated versions of additional regional locales that aren't otherwise available.

**Comment by ausi** [comment]
> In my case I wanted to add translated versions of additional regional locales that aren't otherwise available.

Dynamically? Because statically this should already be possible via `contao.intl.locales` and `contao.intl.enabled_locales`. Translations are handled by the Contao translator.

An event might still make sense though, but I’m not sure how exactly this should look.

**Comment by fritzmg** [comment]
True, that works 👍 

```yaml
# config/config.yaml
contao:
    intl:
        - '+foobar'
```

```php
// contao/languages/en/languages.php
$GLOBALS['TL_LANG']['LNG']['foobar'] = 'Foobar';
```

I'll close this for now. We can reopen should the need arise.
